osx_image: xcode8.1
language: objective-c

before_install:
  - brew update || brew update
  - brew outdated xctool || brew upgrade xctool

script: xctool -project BiftVector.xcodeproj -scheme BiftVector run-tests
